BATTERY_CAPACITY_WH = 2500
MAX_MTTR_MS = 500
MAX_SECURITY_TAX_MS = 75
TRUST_DECAY_ALPHA = 0.85
TRUST_THRESHOLD_CRITICAL = 0.30
MAX_CONCURRENT_NODES = 10

UDP_PORT = 5005
UDP_PACKET_FORMAT = "!9f"
UDP_PACKET_BYTES = 36

DASHBOARD_POLL_INTERVAL_MS = 1000
TRAINING_DATA_FILE = "training_data.csv"

DB_URL = "sqlite+aiosqlite:///./mes.db"
CSV_QUEUE_MAXSIZE = 10000
DB_BATCH_SIZE = 50
UDP_STALE_TIMEOUT_SEC = 2.0
